import type { Metadata } from 'next'

import localFont from 'next/font/local'

import './globals.css'
import Link from 'next/link'

import Footer from '@/components/Footer'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
                    <header className="fixed top-0 w-full pt-5 overflow-hidden text-center backdrop-blur-[6px]">
                        <Link href={'/'} className="link">
                            ↩️ To Home
                        </Link>
                    </header>

                    <main className="flex flex-col pt-5 gap-8 items-center sm:items-start">
                        {children}
                    </main>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
