enum ProjectTool {
    Next = 'next',
    React = 'react',
    TypeScript = 'typescript',
    HTML = 'html',
    TailwindCSS = 'tailwindcss',
    ThreeJS = 'three.js',
    Webcomponents = 'webcomponents',
    ReactHookForm = 'reacthookform',
    Markdown = 'markdown',
    Contentlayer = 'contentlayer',
    I18next = 'i18next',
    Jest = 'jest',
    OpenAI = 'openai',
    NestJs = 'nestjs',
    NodeJs = 'nodejs',
    Swagger = 'swagger',
    TypeORM = 'typeorm',
    PostgreSQL = 'postgresql',
    Multer = 'multer',
    Zod = 'zod',
    Docker = 'docker',
    Sharp = 'sharp',
    Sass = 'sass',
    Yarn = 'yarn',
    Vite = 'vite',
    Leaflet = 'leaflet',
    AntDesign = 'antdesign',
    Bootstrap = 'bootstrap',
    JSON = 'json',
    Redux = 'redux',
    Ky = 'Ky',
    ReduxSaga = 'redux-saga',
    CSS = 'css',
    JavaScript = 'javascript',
    PHP = 'php',
    PHPMailer = 'phpmailer',
    ReactD3Tree = 'react-d3-tree',

    // RTK= 'rtk-query',
    // Axios= 'axios',
    // ReactQuery= 'react-query',
}

export { ProjectTool }
